version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '03:00'
      timezone: 'Asia/Bangkok'
    open-pull-requests-limit: 10
    groups:
      types:
        patterns: ['@types/*']
      rspack:
        patterns: ['@rspack/*']
      changesets:
        patterns: ['@changesets/*']
      biome:
        patterns: ['@biomejs/*']

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
