packages:
  - 'packages/*'
  - 'docs'
  - 'examples/node'

allowBuilds:
  esbuild: set this to true or false

catalog:
  typescript: ^6.0.3
  vitest: ^4.1.6
  '@rspack/core': ^2.0.2
  '@rspack/cli': ^2.0.2
